CREATE DATABASE IF NOT EXISTS users_db;
CREATE DATABASE IF NOT EXISTS products_db;

CREATE USER IF NOT EXISTS 'micro'@'%' IDENTIFIED BY 'arturka1';
GRANT ALL PRIVILEGES ON *.* TO 'micro'@'%';
FLUSH PRIVILEGES;
